version: '3.8'

services:
  converter:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdfmathtranslate
    container_name: pdfmathtranslate
    ports:
      - "7860:7860"
    volumes:
      - ./pdf2zh_files:/app/pdf2zh_files
      - ./healthcheck.py:/app/healthcheck.py
    restart: always
    healthcheck:
      # Use the custom health check script to verify the service is fully functional
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PYTHONUNBUFFERED=1