name: Build and Push Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Security best practices
permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Shallow clones should be disabled for better relevancy of analysis
          fetch-depth: 0
      
      # Set up Docker Buildx for more efficient builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Login to Docker Hub using GitHub secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: googlesky/pdfmathtranslate:latest
          # Enable cache for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Add build metadata
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
      
      # Scan the Docker image for vulnerabilities (security best practice)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'googlesky/pdfmathtranslate:latest'
          format: 'table'
          exit-code: '0'  # Don't fail the build if vulnerabilities are found
          severity: 'CRITICAL,HIGH'